### ISSUE TITLE
Add Digital Ocean and Docker Use Case

### ISSUE THREAD

**Issue by bordenit** [natemcmaster/LettuceEncrypt#69]
**Is your feature request related to a problem? Please describe.**
Add Docker and Digital Ocean Use Case

**Describe the solution you'd like**
Add Docker and Digital Ocean Use Case

**Describe alternatives you've considered**
None

**Additional context**
Issue #14 was helpful, but I think you will increase the use case if you add something obvious to the README.md for Docker.

**Basic Steps for Docker in Digital Ocean droplet (.NET CORE)**

1. Configure your web application per the instructions of this repo.
2. Create Digital Ocean droplet. Under marketplace, there is a Docker image option that has Docker preinstalled.
3. Point your DNS A record at the Digital Ocean Droplet IP.
4. Build container and publish container to Docker Hub.

**Sample Dockerfile**

```dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS env

# Copy files from project into Docker /src folder and build project
WORKDIR /src

#Main Project
COPY /*.csproj /myprojectname
COPY . .

#Publish application to app directory
FROM env AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "myprojectname.dll"]
```

5. Run your container. Assumes your container is working and published to Docker Hub.....
> docker run -v ~/x509stores/:/root/.dotnet/corefx/cryptography/x509stores/ --name mycontainername -d -p 80:80 -p 443:443 -e "ASPNETCORE_ENVIRONMENT=Production" -e ASPNETCORE_URLS="http://+;https://+" -e ASPNETCORE_HTTPS_PORT=443 mydockerhubaccount/mycontainername

6. Navigate to your domain name in the browser.

You could have a $5/month website this way that integrates easily with the CI/CD pipeline. I tested these basic steps and it works, but maybe more details are needed. I think it's practical for smaller IT companies who don't want to spend a ton of money to host a website.

Yeah, that's kind of a mess, but if there is value in it, maybe I'll write the instructions better.

**Comment by ffMathy** [comment]
Could use Pull Dog to automatically create test environments for each pull request as well, based on the Docker compose file of this.

https://github.com/apps/pull-dog

**Comment by bordenit** [comment]
> Could use Pull Dog to automatically create test environments for each pull request as well, based on the Docker compose file of this.
> https://github.com/apps/pull-dog

GitHub Actions is also pretty flexible. You can build and run containers in it without installing any other Docker dependencies. For example, this is how I build and test a container with xUnit and Selenium. **It does not include instructions for Selenium or xUnit, so you can reach your own conclusions there, but you can apply it to other testing frameworks as well.** But if you can run dotnet test, this will probably work. I think Docker compose works in actions as well, although you might run into resource issues. I tried to build an selenium grid in actions once and it died. Other than that, I haven't played with it too much, but at least a single container works fairly well.

The Pull Request Workflow (AKA. Continuous Integration)
```
name: CI
on: 
  pull_request:
    branches: 
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Container - Docker Build
      run: docker build -t <mydockerhubaccount>/<mydockerhubcontainer> <mymainprojectfolder>
    - name: Build Container - Docker Run
      run: docker run -v ~/x509stores/:/root/.dotnet/corefx/cryptography/x509stores/ -t -d -p 80:80 -p 443:443 -e "ASPNETCORE_ENVIRONMENT=Development" --name <localcontainername> <mydockerhubaccount>/<mydockerhubcontainer>
    - name: Print Chrome Version
      run: google-chrome --version
    - name: xUnit Test Preparation - Add Chromedriver To Path Environment Variable
      run: PATH="/<mytestprojectfolder>/chromedriver:${PATH}"
    - name: xUnit Test Preparation - Set File Permissions for Chromedriver
      run: chmod a+x "<mytestprojectfolder>/chromedriver"
    - name: xUnit Test Preparation - Load the Contact Page - Ensures Ports are Open & Prints Page
      run:  wget -qO- "http://localhost/contact"
    - name: Run xUnit Tests
      run: dotnet test <mytestprojectfolder>
```
The Publish Workflow (AKA. CD)
Here is how I publish to Digital Ocean:
```
name: dockerpublish

on: 
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        dockerHubUsername: ${{secrets.dockerHubUsername}}
        dockerHubPassword: ${{secrets.dockerHubPassword}}
    steps:
    - uses: actions/checkout@v1
    - name: Build Container - Docker Hub Login
      run: echo ${{secrets.dockerHubPassword}} | docker login -u ${{secrets.dockerHubUsername}} --password-stdin
    - name: Build Container - Docker Build
      run: docker build -t  <mydockerhubaccount>/<mydockerhubcontainer> <mymainprojectfolder>
    - name: Build Container - Push to Docker Hub
      run: docker push <mydockerhubaccount>/<mydockerhubcontainer>:latest
    - name: Build Container - Docker Hub Logout
      run: docker logout
    - name: Digital Ocean Preparation - Output Private Key to Text File for Login
      run: echo "${{secrets.digitalOceanPrivateKey}}" >> key.txt
    - name: Digital Ocean Preparation - Set Permissions on Private Key Text File
      run: chmod 600 key.txt
    - name: Digital Ocean Preparation - Set File Permissions for Deployment Script
      run: chmod a+x scripts/containermaint.sh
    - name: Digital Ocean Preparation - Docker Hub Login
      run: ssh -o "StrictHostKeyChecking=no" -i key.txt root@<mycontainerip> "echo ${{secrets.dockerHubPassword}} | docker login -u ${{secrets.dockerHubUsername}} --password-stdin"
    - name: Digital Ocean Preparation - Pull Website Container From Docker Hub and Publish to Digital Ocean Droplet
      run: ssh -o "StrictHostKeyChecking=no" -i key.txt root@<mycontainerip> 'bash -s' < scripts/containermaint.sh
    - name: Digital Ocean Preparation - Docker Hub Logout
      run: ssh -o "StrictHostKeyChecking=no" -i key.txt root@<mycontainerip> "docker logout > /dev/null"
    - name: Delete Private Key Text File
      run: rm key.txt
    
```
Slap another test in there after the publish to test the https against the public facing container or test if the local solution to test let's encrypt will work in actions.

Here is the container maintenance script referenced above to remove all containers from the droplet....

```bash
#!/bin/sh
echo $dockerHubPassword | docker login -u $dockerHubUsername --password-stdin
CONTAINERID=$(docker ps -a -q)
docker stop $CONTAINERID > /dev/null
docker rm $CONTAINERID 2>/dev/null || true
docker pull <mydockerhubaccount>/<mydockerhubcontainer>
docker run -v ~/x509stores/:/root/.dotnet/corefx/cryptography/x509stores/ --name <localcontainername> -d -p 80:80 -p 443:443 -e "ASPNETCORE_ENVIRONMENT=Production" -e ASPNETCORE_URLS="http://+;https://+" -e ASPNETCORE_HTTPS_PORT=443 <mydockerhubaccount>/<mydockerhubcontainer>
```
